# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Types-ReadOnly`
	:test-requirement    [ :on "Test::More 0.96"^^:CpanId ];
	:test-requirement    [ :on "Test::Fatal"^^:CpanId ];
	:test-requirement    [ :on "Test::Requires"^^:CpanId ];
	:runtime-requirement [ :on "Type::Tiny 1.006000"^^:CpanId ];
	.

